config/routes.rb
Rails.application.routes.draw do
  resources :meal_templates
  devise_for :users
  root 'pages#home'

  get 'pages/home'

  get '/login/', to: 'pages#login', as: 'login'
  get '/signup/', to: 'pages#signup', as: 'signup'

  get '/payments/', to: 'pages#payments', as: 'payments'

  post '/payments/', to: 'pages#create_payment_method', as: 'create_payment_method'

  get '/meal_templates/embed/:id', to: 'meal_templates#show_embed', as: 'show_embed'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal_template.rb
class MealTemplate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :check_for_payment_method, if: :user_signed_in?

  def check_for_payment_method

    unless current_user.stripe_customer_id

      #redirect_to payments_path

    end

  end

  def configure_permitted_parameters

		registration_params = [:email, :password]
		devise_parameter_sanitizer.permit(:sign_up, keys: registration_params)
		devise_parameter_sanitizer.permit(:sign_in, keys: registration_params)
		devise_parameter_sanitizer.permit(:account_update, keys: registration_params)

	end


	def after_sign_in_path_for(user)

		unless current_user.id

			payments_path

		else

      if current_user.stripe_customer_id
			   root_path
      else
        payments_path
      end

    end

  end

end

app/controllers/meal_templates_controller.rb
class MealTemplatesController < ApplicationController
  before_action :set_meal_template, only: [:show, :embed_show, :edit, :update, :destroy]

  # GET /meal_templates
  # GET /meal_templates.json
  def index
    @meal_templates = MealTemplate.all
  end

  # GET /meal_templates/1
  # GET /meal_templates/1.json
  def show
  end

  def show_embed
    @meal_template = MealTemplate.find(params[:id])
    @hide_navigation = true
  end

  # GET /meal_templates/new
  def new
    @meal_template = MealTemplate.new
  end

  # GET /meal_templates/1/edit
  def edit
  end

  # POST /meal_templates
  # POST /meal_templates.json
  def create
    @meal_template = MealTemplate.new(meal_template_params)

    respond_to do |format|
      if @meal_template.save
        format.html { redirect_to @meal_template, notice: 'Meal template was successfully created.' }
        format.json { render :show, status: :created, location: @meal_template }
      else
        format.html { render :new }
        format.json { render json: @meal_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_templates/1
  # PATCH/PUT /meal_templates/1.json
  def update
    respond_to do |format|
      if @meal_template.update(meal_template_params)
        format.html { redirect_to @meal_template, notice: 'Meal template was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal_template }
      else
        format.html { render :edit }
        format.json { render json: @meal_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_templates/1
  # DELETE /meal_templates/1.json
  def destroy
    @meal_template.destroy
    respond_to do |format|
      format.html { redirect_to meal_templates_url, notice: 'Meal template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_template
      @meal_template = MealTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_template_params
      params.require(:meal_template).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @meal_templates = MealTemplate.all
  end

  def login

    @hide_navigation = true

  end

  def signup

    @hide_navigation = true

  end

  def payments

    @hide_navigation = true

  end

  def create_payment_method

    if user_signed_in?

    ccNumber = params[:cc_number]
    ccName = params[:cc_name]
    ccExpMonth = params[:cc_exp_month]
    ccExpYear = params[:cc_exp_year]
    ccCVC = params[:cc_cvc]

    if (ccNumber && ccName && ccExpMonth && ccExpYear)

      Stripe.api_key = ENV["STRIPE_LIVE_SECRET_KEY"]

      token = Stripe::Token.create(

        :card => {
          :number => ccNumber,
          :exp_month => ccExpMonth,
          :exp_year => ccExpYear,
          :cvc => ccCVC

        },
      )

      customer = Stripe::Customer.create(
        :description => "Customer for mealtemplate",
        :source => token.id # obtained with Stripe.js
      )

      Stripe::Subscription.create(
        :customer => customer.id,
        :items => [
          {
            :plan => "basic",
          },
        ]
      )

      current_user.update(:stripe_customer_id => customer.id)

      redirect_to root_path
    else

      redirect_to payments_path

    end

  else
    redirect_to login_path
  end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meal_templates_helper.rb
module MealTemplatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navigation.html.erb
<div class="navigation">

  <ul class="horizontal-list navigation__left">

    <li><%= link_to 'Title', root_path %></li>
  </ul>

  <ul class="horizontal-list navigation__right">
    <% if user_signed_in? %>
      <li>
        <a>My Account</a>
      </li>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to 'Login', login_path %>
      </li>
      <li>
        <%= link_to 'Signup', signup_path %>
      </li>
    <% end %>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mealtemplate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <% unless @hide_navigation %>
      <%= render 'layouts/navigation' %>
      <div class="main-content">
    <% else %>

      <div class="main-content hidden_nav">

    <% end %>

      <% if notice %><p class="notice"><%= notice %></p><% end %>
      <% if alert %><p class="alert"><%= alert %></p><% end %>

      <%= yield %>
    </div>

    <%= render 'meal_templates/modal_form' %>

  </body>
</html>

app/views/meal_templates/_form.html.erb
<%= form_for(meal_template) do |f| %>
  <% if meal_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal_template.errors.count, "error") %> prohibited this meal_template from being saved:</h2>

      <ul>
      <% meal_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meal_templates/_index_show.html.erb
<div class="card meal-template-index">
  <%= meal_template.name %>
  <br><br>
  <%= link_to 'View Details', meal_template %>
  <%= link_to 'Embed this Template', show_embed_path(meal_template.id) %>
  <%= link_to 'Edit', edit_meal_template_path(meal_template) %>
  <%= link_to 'Destroy', meal_template, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/meal_templates/_modal_form.html.erb
<div class="modal-container" id="meal_template_form" style="display: none;">

  <div class="modal-content">
    <%= form_for(MealTemplate.new) do |f| %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/meal_templates/edit.html.erb
<h1>Editing Meal Template</h1>

<%= render 'form', meal_template: @meal_template %>

<%= link_to 'Show', @meal_template %> |
<%= link_to 'Back', meal_templates_path %>

app/views/meal_templates/embed_show.html.erb
<p>
  <strong>Name:</strong>
  <%= @meal_template.name %>
</p>

app/views/meal_templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meal Templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meal_templates.each do |meal_template| %>
      <tr>
        <td><%= meal_template.name %></td>
        <td><%= link_to 'Show', meal_template %></td>
        <td><%= link_to 'Edit', edit_meal_template_path(meal_template) %></td>
        <td><%= link_to 'Destroy', meal_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal Template', new_meal_template_path %>

app/views/meal_templates/new.html.erb
<h1>New Meal Template</h1>

<%= render 'form', meal_template: @meal_template %>

<%= link_to 'Back', meal_templates_path %>

app/views/meal_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meal_template.name %>
</p>

<%= link_to 'Edit', edit_meal_template_path(@meal_template) %> |
<%= link_to 'Back', meal_templates_path %>

app/views/meal_templates/show_embed.html.erb
<p>
  <strong>Name:</strong>
  <%= @meal_template.name %>
</p>

<a>CLCICKCKCKMMSSKMSKM</a>

app/views/pages/home.html.erb
<div class="content">

  <% @meal_templates.each do |meal_template| %>
    <%= render 'meal_templates/index_show', meal_template: meal_template %>
  <% end %>

  <a class="open-modal" data-modal-id="meal_template_form">Create Meal Template</a>
</div>

app/views/pages/login.html.erb
<div class="signup-background"></div>

<div class="signup-container">

  <div class="signup-container__form">
    <div class="signup-container__form__header">
      <header>Title</header>
    </div>
    <div class="signup-container__form__container">
      <%= form_for(:user, url: session_path(:user)) do |f| %>
        <div class="field">
          <%= f.label :email, class: 'signup-container__form__label' %><br />
          <%= f.email_field :email, autofocus: true, class: 'signup-container__form__input' %>
        </div>

        <div class="field">
          <%= f.label :password, class: 'signup-container__form__label' %><br />
          <%= f.password_field :password, autocomplete: "off", class: 'signup-container__form__input' %>
        </div>

        <div class="actions">
          <%= f.submit "Log in" %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/pages/payments.html.erb
<div class="signup-background"></div>

<div class="signup-container">

  <div class="signup-container__form">
    <div class="signup-container__form__header">
      <header>Enter Your Payment Information</header>
    </div>

    <div class="signup-container__form__container">
      <form method='post' action='/payments'>

        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

        <div class="field">
          <label class='signup-container__form__label'>Credit Card Number</label><br />
          <input class='signup-container__form__input' name='cc_number' type='text'></input>
        </div>

        <div class="field">
          <label class='signup-container__form__label'>Name on Card</label><br />
          <input class='signup-container__form__input' name='cc_name' type='text'></input>
        </div>

        <div class="field">
          <label class='signup-container__form__label'>EXP Month</label><br />
          <select name='cc_exp_month'>
            <option value="1">01</option>
            <option value="2">02</option>
            <option value="3">03</option>
            <option value="4">04</option>
            <option value="5">05</option>
            <option value="6">06</option>
            <option value="7">07</option>
            <option value="8">08</option>
            <option value="9">09</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>

          </select>
        </div>

        <div class="field">
          <label class='signup-container__form__label'>EXP Year</label><br />
          <select name='cc_exp_year'>
            <% currentYear = Time.now.year %>
            <% for i in 0..9 do %>
              <% optionYear = currentYear + i %>
              <option value="<%= optionYear %>"><%= optionYear %></option>
            <% end %>
          </select>
        </div>

        <div class="field">
          <label class='signup-container__form__label'>CVC</label><br />
          <input class='signup-container__form__input' name='cc_cvc' type='text'></input>
        </div>

        <div class="actions">
          <input type="submit" value="Add Payment Method"></input>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/pages/signup.html.erb
<div class="signup-background"></div>

<div class="signup-container">

  <div class="signup-container__form">
    <div class="signup-container__form__header">
      <header>Title</header>
    </div>
    <div class="signup-container__form__container">
      <%= form_for(:user, url: registration_path(:user)) do |f| %>

        <div class="field">
          <%= f.label :email, class: 'signup-container__form__label' %><br />
          <%= f.email_field :email, autofocus: true, class: 'signup-container__form__input' %>
        </div>

        <div class="field">
          <%= f.label :password, class: 'signup-container__form__label' %>
          <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off", class: 'signup-container__form__input' %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, class: 'signup-container__form__label' %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off", class: 'signup-container__form__input' %>
        </div>

        <div class="actions">
          <%= f.submit "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>

</div>